In [62]:
import numpy as np
import matplotlib.pyplot as plt

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [63]:
A = np.asfarray([[-1,3,2,1],[3,-3,1,5],[2,1,2,-4],[1,5,-4,1]])

V_A = np.identity(4)

B = 2*np.identity(100)

V_B = np.identity(100)

B[0][1] = -1
B[99][98] = -1


i = 1
while i < np.shape(B)[0]-1:
    B[i][i-1] = -1
    B[i][i+1] = -1
    i += 1

print(np.linalg.eig(A)[0])

[-7.63555541 -3.57189391  3.71738834  6.49006097]


In [64]:
def sign(x):
    if x >= 0:
        return 1
    else:
        return -1
    
def trace(M):
    sum = 0
    for i in range(np.shape(M)[0]):
        sum += M[i][i]
    return sum

In [65]:
def jacobi(A,V,sweeps):
    dim = np.shape(A)[0]
    #symm = 0
    u = 0
    while u < sweeps:

        p = 0
        q = 0

        while p < dim:                           #choose p
            q = p + 1
            while q < dim:                          #choose q

                if A[p][q] == 0:
                    q += 1
                    continue

                theta = 0.5*((A[q][q]-A[p][p])/(A[p][q]))

                t = (sign(theta))/(np.abs(theta)+((theta**2)+1)**0.5)
                #t = 1/(theta-(theta**2+1)**0.5)
                #t = -theta + ((theta**2)+1)**0.5

                phi = np.arctan(t)

                if np.abs(phi) > (np.pi/4):
                    t = 1/(2*theta)
                    phi = np.arctan(t)

                c = 1/((t**2+1)**0.5)
                s = t*c

                tau = s/(1+c)

                A[p][p] -= t*A[p][q]
                A[q][q] += t*A[p][q]

                r = 0
                while r < dim:
                    
                    f = A[r][p]
                    g = A[r][q]

                    h = V[r][p]
                    o = V[r][q]

                    V[r][p] = c*h - s*o
                    V[r][q] = s*h + c*o

                    if r == p or r == q:
                        r += 1
                        continue
                        
                    #symm += np.abs(A[r][p]-A[p][r])
                    #symm += np.abs(A[r][q]-A[q][r])

                    A[r][p] -= s*(g + tau*f)
                    A[r][q] += s*(f - tau*g)

                    A[p][r] = A[r][p]
                    A[q][r] = A[r][q]

                    r += 1
                
                A[p][q] = 0
                A[q][p] = 0
                
                q += 1
                
            p += 1
        
        u += 1
    return A,V

In [69]:
Eigenvalues, Eigenvectors = jacobi(A,V_A,7)

print("Eigenvalue 1: ", Eigenvalues[0][0])

print("Eigenvalue 2: ", Eigenvalues[1][1])

print("Eigenvalue 3: ", Eigenvalues[2][2])

print("Eigenvalue 4: ", Eigenvalues[3][3])

print("Every coloumn represents one Eigenvector: \n", Eigenvectors)

Eigenvalue 1:  -3.571893906192047
Eigenvalue 2:  -7.635555409388156
Eigenvalue 3:  3.717388344336183
Eigenvalue 4:  6.490060971244021
Every coloumn represents one Eigenvector: 
 [[ 0.77377953 -0.18383508  0.59701011  0.10511345]
 [-0.22799557  0.76940879  0.46704217  0.37134855]
 [-0.48216793 -0.26964009  0.63663743 -0.53805305]
 [-0.34175627 -0.54909835  0.14192717  0.74936662]]


In [67]:
B,V_B = np.around(jacobi(B,V_B,6),5)

In [68]:
print(trace(B))

for i in range(np.shape(B)[0]):
    print(B[i][i])

200.00002
3.99835
0.00454
1.84479
2.09382
3.98512
0.02004
0.53188
3.42516
3.0884
0.61916
1.90668
2.1558
3.99614
0.16078
0.45024
3.99065
3.81347
1.65952
1.78268
2.33964
2.21697
0.04477
0.13766
2.27913
3.86238
1.72093
1.59832
3.50965
3.5497
0.02252
1.24182
2.40159
2.46235
0.00901
0.3392
3.62531
2.64165
1.53765
1.18463
3.96462
3.24002
0.2424
0.03539
3.94016
2.58243
1.12823
1.35835
3.58832
2.87177
0.27307
0.9643
3.69483
2.92733
0.06092
1.41757
3.95144
1.07267
2.75818
2.70025
0.00107
1.47736
3.92231
3.90422
0.09575
0.30537
3.72685
2.52264
1.29975
1.01801
2.81537
3.0357
0.18661
0.91159
3.88409
3.38084
0.75998
0.07781
3.97586
0.71178
3.83871
3.75739
0.11592
0.21377
3.19062
2.98199
0.37468
0.66482
3.78623
3.14006
0.41172
0.85994
3.66078
3.33518
0.57483
0.80938
3.46812
0.49035
3.28822
2.0311
1.9689
