In [213]:
import numpy as np
import matplotlib.pyplot as plt

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [214]:
A = np.asfarray([[-1,3,2,1],[3,-3,1,5],[2,1,2,-4],[1,5,-4,1]])

V_A = np.identity(4)

B = 2*np.identity(100)

V_B = np.identity(100)

B[0][1] = -1
B[99][98] = -1


i = 1
while i < np.shape(B)[0]-1:
    B[i][i-1] = -1
    B[i][i+1] = -1
    i += 1

print(np.linalg.eig(A))

EigResult(eigenvalues=array([-7.63555541, -3.57189391,  3.71738834,  6.49006097]), eigenvectors=array([[-0.18383508,  0.77377953, -0.59701011,  0.10511345],
       [ 0.76940879, -0.22799557, -0.46704217,  0.37134855],
       [-0.26964009, -0.48216793, -0.63663743, -0.53805305],
       [-0.54909835, -0.34175627, -0.14192717,  0.74936662]]))


In [215]:
def sign(x):
    if x >= 0:
        return 1
    else:
        return -1
    
def trace(M):
    sum = 0
    for i in range(np.shape(M)[0]):
        sum += M[i][i]
    return sum

In [216]:
def jacobi(A,V,sweeps):
    dim = np.shape(A)[0]
    #symm = 0
    u = 0
    while u < sweeps:

        p = 0
        q = 0

        while p < dim:                           #choose p
            q = p + 1
            while q < dim:                          #choose q

                if A[p][q] == 0:
                    q += 1
                    continue

                theta = 0.5*((A[q][q]-A[p][p])/(A[p][q]))

                t = (sign(theta))/(np.abs(theta)+((theta**2)+1)**0.5)
                #t = 1/(theta-(theta**2+1)**0.5)
                #t = -theta + ((theta**2)+1)**0.5

                phi = np.arctan(t)

                if np.abs(phi) > (np.pi/4):
                    t = 1/(2*theta)
                    phi = np.arctan(t)

                c = 1/((t**2+1)**0.5)
                s = t*c

                tau = s/(1+c)

                A[p][p] -= t*A[p][q]
                A[q][q] += t*A[p][q]

                r = 0
                while r < dim:
                    
                    arp_old = A[r][p]
                    arq_old = A[r][q]

                    vrp_old = V[r][p]
                    vrq_old = V[r][q]

                    V[r][p] = c*vrp_old - s*vrq_old
                    V[r][q] = s*vrp_old + c*vrq_old

                    if r == p or r == q:
                        r += 1
                        continue
                        
                    #symm += np.abs(A[r][p]-A[p][r])
                    #symm += np.abs(A[r][q]-A[q][r])

                    A[r][p] -= s*(arq_old + tau*arp_old)
                    A[r][q] += s*(arp_old - tau*arq_old)

                    A[p][r] = A[r][p]
                    A[q][r] = A[r][q]

                    r += 1
                
                A[p][q] = 0
                A[q][p] = 0
                
                q += 1
                
            p += 1
        
        u += 1
    return A,V

In [217]:
A = np.asfarray([[-1,3,2,1],[3,-3,1,5],[2,1,2,-4],[1,5,-4,1]])
V_A = np.identity(4)

A, V_A = jacobi(A,V_A,7)

print(V_A)

dim = np.shape(A)[0]

eigenvecs = np.asfarray([[0,0,0,0]])

for i in range(dim):
    eigenvec = np.asfarray([])
    for j in range(dim):
        eigenvec = np.append(eigenvec, V_A[j][i])
    #print("Eigenvector ", i+1, ": ", eigenvec)
    print("Eigenvalue ", i+1, ": ", A[i][i])
    print("Eigenvector ", i+1, ": ", eigenvec)
    eigenvecs = np.r_[eigenvecs,[eigenvec]]
    #print("Eigenvector ", i+1, ": ", V_A[i])

[[ 0.77377953 -0.18383508  0.59701011  0.10511345]
 [-0.22799557  0.76940879  0.46704217  0.37134855]
 [-0.48216793 -0.26964009  0.63663743 -0.53805305]
 [-0.34175627 -0.54909835  0.14192717  0.74936662]]
Eigenvalue  1 :  -3.571893906192047
Eigenvector  1 :  [ 0.77377953 -0.22799557 -0.48216793 -0.34175627]
Eigenvalue  2 :  -7.635555409388156
Eigenvector  2 :  [-0.18383508  0.76940879 -0.26964009 -0.54909835]
Eigenvalue  3 :  3.717388344336183
Eigenvector  3 :  [0.59701011 0.46704217 0.63663743 0.14192717]
Eigenvalue  4 :  6.490060971244021
Eigenvector  4 :  [ 0.10511345  0.37134855 -0.53805305  0.74936662]


C:\Users\Dustin\AppData\Local\Temp\ipykernel_14732\3148253421.py:20: RuntimeWarning: overflow encountered in scalar power
  t = (sign(theta))/(np.abs(theta)+((theta**2)+1)**0.5)


In [218]:
A = np.asfarray([[-1,3,2,1],[3,-3,1,5],[2,1,2,-4],[1,5,-4,1]])
dim = np.shape(A)[0]

test1 = np.dot(A,eigenvecs[1])
for i in range(dim):
    print(test1[i]/eigenvecs[1][i])


test2 = np.dot(A,eigenvecs[2])
for i in range(dim):
    print(test2[i]/eigenvecs[2][i])

test3 = np.dot(A,eigenvecs[3])
for i in range(dim):
    print(test3[i]/eigenvecs[3][i])

test4 = np.dot(A,eigenvecs[4])
for i in range(dim):
    print(test4[i]/eigenvecs[4][i])

-3.571893906192046
-3.5718939061920447
-3.5718939061920447
-3.5718939061920505
-7.635555409388158
-7.635555409388157
-7.6355554093881555
-7.635555409388158
3.7173883443361837
3.7173883443361824
3.717388344336183
3.7173883443361744
6.49006097124402
6.490060971244017
6.490060971244022
6.49006097124402


In [222]:
B,V_B = jacobi(B,V_B,9)

In [220]:
#print(trace(B))
dim = np.shape(B)[0]

eigenvecs = np.asfarray([np.zeros(100)])

for i in range(dim):
     print("Eigenvalue ", i+1, ": ", B[i][i])
     eigenvec = np.asfarray([])
     for j in range(dim):
           eigenvec = np.append(eigenvec, V_B[j][i])
     eigenvecs = np.r_[eigenvecs,[eigenvec]]
     # print("Eigenvector ", i+1, ": ", eigenvec)


Eigenvalue  1 :  3.998932322348607
Eigenvalue  2 :  0.003994533038403579
Eigenvalue  3 :  1.8446324030186783
Eigenvalue  4 :  2.093281912606155
Eigenvalue  5 :  3.9846083782988098
Eigenvalue  6 :  0.01545384366575886
Eigenvalue  7 :  0.5318829313989398
Eigenvalue  8 :  3.4251679443214074
Eigenvalue  9 :  3.088408372487741
Eigenvalue  10 :  0.6191599417034414
Eigenvalue  11 :  1.9067198293575767
Eigenvalue  12 :  2.1553654975823835
Eigenvalue  13 :  3.9961546926597187
Eigenvalue  14 :  0.16129335551222887
Eigenvalue  15 :  0.45028577669235337
Eigenvalue  16 :  3.9913019593183643
Eigenvalue  17 :  3.8133453507745556
Eigenvalue  18 :  1.659512752988393
Eigenvalue  19 :  1.7826954843448806
Eigenvalue  20 :  2.340487006898344
Eigenvalue  21 :  2.2173035360873947
Eigenvalue  22 :  0.04711165357606458
Eigenvalue  23 :  0.1377116621806103
Eigenvalue  24 :  2.279030675911252
Eigenvalue  25 :  3.8622883449706964
Eigenvalue  26 :  1.7209693192420115
Eigenvalue  27 :  1.5983857853401087
Eigenvalue

In [224]:
B = 2*np.identity(100)
dim = np.shape(B)[0]
B[0][1] = -1
B[99][98] = -1
i = 1
while i < dim-1:
    B[i][i-1] = -1
    B[i][i+1] = -1
    i += 1



# test1 = np.dot(B,eigenvecs[1])
# for i in range(dim):
#     print(test1[i]/eigenvecs[1][i])

test3 = np.dot(B,eigenvecs[3])
for i in range(dim):
    print(test3[i]/eigenvecs[3][i])

1.8447528066517738
1.8449332696119123
1.8446921044102322
1.8442308950343007
1.8448455878055647
1.844799967735354
1.8447222082224435
1.8443987402976934
1.844770950052998
1.8445337555133972
1.844863719607327
1.844552882690083
1.8448208387212357
1.8445898847692077
1.8448473446979965
1.8444573178552042
1.8455272225023729
1.8445867620494563
1.8447601430949736
1.8444671833957387
1.8418334935089977
1.8445136627203422
1.8444400740030533
1.8446102990502982
1.8444666804937235
1.8442812616814137
1.8443376125124815
1.8447641240808104
1.8446449137981071
1.8441267918502233
1.8446066328340929
1.8446594117659285
1.8445440629601066
1.844055929295532
1.844731962383426
1.8446333037485263
1.844563890525138
1.8430782560746322
1.844706717505036
1.844569145244744
1.8446385951941757
1.847352067518048
1.8447184928291538
1.8445743117188016
1.8446596646044704
1.845123727090601
1.8448445635235935
1.8448975580905054
1.8445054910770156
1.844737276827544
1.844997183175788
1.8448798409792866
1.8446379922348783
1.8447