In [1]:
import numpy as np


import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [15]:
def f(x):
    return x*np.exp(x)-1

def df(x):
    return np.exp(x)+x*np.exp(x)

def phi1(x):
    return np.exp(-x)

def phi2(x):
    return (1+x)/(1+np.exp(x))

def phi3(x):
    return 1+x-x*np.exp(x)

x0 = 0.5

In [16]:
x = np.asfarray([x0])
i = 0
while i < 10:
    x = np.append(x,phi1(x))
    i += 1

print(x)

[0.5        0.60653066 0.60653066 ... 0.56755963 0.56755963 0.56690721]


In [17]:
x = np.asfarray([x0])
i = 0
while i < 10:
    x = np.append(x,phi2(x))
    i += 1

print(x)

[0.5        0.566311   0.566311   ... 0.56714329 0.56714329 0.56714329]


In [18]:
x = np.asfarray([x0])
i = 0
while i < 10:
    x = np.append(x,phi3(x))
    i += 1

print(x)

[ 0.5         0.67563936  0.67563936 ...  0.92492068  0.92492068
 -0.40742241]


In [20]:
x = np.asfarray([x0])
i = 0
while i < 10:
    x = np.append(x, x - f(x)/df(x))
    i += 1

print(x)

[0.5        0.57102044 0.57102044 ... 0.56714329 0.56714329 0.56714329]
