In [2]:
import numpy as np

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [25]:
x0 = np.asfarray([1,1,1])

J = np.asfarray([[2*x0[0],1,0],[1,2*x0[1],0],[x0[1],x0[0],-3*x0[2]]])

A = np.asfarray([[1,1,1],[2,6,2],[3,4,5]])

b = np.asfarray([11,7,0])

Jinv = s.matrix_inverse(J,b)

J = np.asfarray([[2*x0[0],1,0],[1,2*x0[1],0],[x0[1],x0[0],-3*x0[2]]])

[[ 2.  1.  0.]
 [ 1.  2.  0.]
 [ 1.  1. -3.]]
