In [1]:
import numpy as np

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [2]:
a = np.asfarray([1,1,1,1,1,1,1,1,1,1])       #ignorier den ersten Wert
b = np.asfarray([2,2,2,2,2,2,2,2,2,2])
c = np.asfarray([-1,-1,-1,-1,-1,-1,-1,-1,-1,-1])        #ignorier den letzten Wert

vecb = np.array([0,-1,2,-3,4,-5,6,-7,8,-9])


N = np.shape(b)[0]

print(N)

10


In [3]:
alpha = c[N-1]
beta = a[0]
gamma = -b[0]

##########################################

b[0] = b[0] - gamma


b[N-1] = b[N-1] - (alpha*beta)/gamma


#a[1] = 0
#c[N-2] = 0

print(a)
print(b)
print(c)

u = np.zeros(N)
u[0] = gamma
u[N-1] = alpha

v = np.zeros(N)
v[0] = 1
v[N-1] = beta/gamma

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4.  2.  2.  2.  2.  2.  2.  2.  2.  1.5]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [4]:
L1,R1,y = s.tridiag_LU_decomp(a,b,c,vecb)

L2,R2,z = s.tridiag_LU_decomp(a,b,c,u)

x = y - ((s.matrix_dot(v,y))/(1+(s.matrix_dot(v,z))))*z

print("Solution: ", x)

Solution:  [ 2.         -1.03658537  0.92682927 -1.18292683  1.56097561 -2.06097561
  2.43902439 -3.18292683  3.07317073 -5.03658537]
