In [2]:
import numpy as np

In [3]:
a = np.array([0,1,1,1,1,1,1,1,1,1])       #ignorier den ersten Wert
b = np.array([2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0])
c = np.array([-1,-1,-1,-1,-1,-1,-1,-1,-1,0])        #ignorier den letzten Wert

vecb = np.array([1,-1,1,-1,1,-1,1,-1,1,-1])


N = np.shape(b)[0]

print(N)

10


In [4]:
alpha = -1
beta = 1
gamma = -b[0]

##########################################

b[0] = b[0] - gamma


b[N-1] = b[N-1] - (alpha*beta)/gamma


a[1] = 0
c[N-2] = 0

print(a)
print(b)
print(c)

[0 0 1 1 1 1 1 1 1 1]
[4.  2.  2.  2.  2.  2.  2.  2.  2.  1.5]
[-1 -1 -1 -1 -1 -1 -1 -1  0  0]


In [5]:
f = c

e = np.zeros(N)

d = np.zeros(N)          #ignorier den ersten Wert

##############################################################################################################

e[0] = b[0]
d[1] = a[1]/e[0]

i = 1

while i < N:                    #BERECHNUNG VON e,d,f. FUNKTIONIERT
    e[i] = b[i] - d[i]*f[i-1]
    if (i+1) == N:
        i = i + 1
        continue
    d[i+1] = a[i+1]/e[i]
    i += 1


L = np.identity(N)
R = np.identity(N)

j = 0

while j < N:                                      #EINSETZEN IN MATRIZEN L,R FUNKTIONIERT!
    R[j][j] = e[j]
    if j == N-1:
        j += 1
        continue
    L[j+1][j] = d[j+1]
    R[j][j+1] = f[j]
    j += 1


#print(np.matrix(d))
print("L: \n", np.matrix(L))

#print(np.matrix(e))#print(np.matrix(f))

print("\n R: \n", np.matrix(R))

#LR-Zerlegung FUNKTIONIERT, HABS GETESTET

L: 
 [[1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.5        1.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.4        1.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.41666667 1.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.4137931  1.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.41428571
  1.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.41420118 1.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.41421569 1.         0.        ]
 [0.         0.         

In [6]:
x = np.zeros(N)

y = np.zeros(N)

y[0] = vecb[0]

i = 1
while i < N:                          #Berechnung von y, FUNKTIONIERT, HABS GECHECKT
    j = 0
    y[i] = vecb[i]
    while j < i:
        y[i] -= L[i][j]*y[j]
        j += 1
    i += 1

#y = np.around(y,5)

#print(y)

x[N-1] = y[N-1]/(R[N-1][N-1])

i = N-2                                 #Berechnung von x, FUNKTIONIERT HABS GETESTET
while i >= 0:
    j = N-1
    x[i] = y[i]
    while j > i:
        x[i] -=  R[i][j]*x[j]
        j -= 1
    x[i] = x[i]/R[i][i]
    i -= 1


#x = np.around(x,5)

print("Das ist die Lösung x des LGS mit Tridiagonalen Matrizen: ", x)

Das ist die Lösung x des LGS mit Tridiagonalen Matrizen:  [ 0.17690355 -0.29238579  0.41522843 -0.46192893  0.49137056 -0.47918782
  0.53299492 -0.41319797  0.70659898 -1.13773266]


In [27]:
import sys

sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises/Blatt2")

import shortcuts as s

A = np.asfarray([[3,-1,1,4,1],[1,0,1,1,1],[-1,-1,-1,-1,-1],[0,0,0,7,2],[3,4,-3,4,1]])

b = np.asfarray([1,-1,1,-1,1])

s.matrix_inverse(A)

array([[ 0.21875,  0.21875,  0.15625, -0.1875 ,  0.09375],
       [ 0.     , -1.     , -1.     , -0.     ,  0.     ],
       [ 0.25   , -1.25   , -1.25   , -0.     , -0.25   ],
       [ 0.1875 , -0.8125 , -0.4375 ,  0.125  , -0.0625 ],
       [-0.65625,  2.84375,  1.53125,  0.0625 ,  0.21875]])