In [53]:
import numpy as np

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [54]:
a = np.asfarray([1,1,1,1,1,1,1,1,1,1])       #ignorier den ersten Wert
b = np.asfarray([2,2,2,2,2,2,2,2,2,2])
c = np.asfarray([-1,-1,-1,-1,-1,-1,-1,-1,-1,-1])        #ignorier den letzten Wert

vecb = np.array([1,-1,1,-1,1,-1,1,-1,1,-1])


N = np.shape(b)[0]

print(N)

10


In [55]:
alpha = c[N-1]
beta = a[0]
gamma = -b[0]

##########################################

b[0] = b[0] - gamma


b[N-1] = b[N-1] - (alpha*beta)/gamma


#a[1] = 0
#c[N-2] = 0

print(a)
print(b)
print(c)

u = np.zeros(N)
u[0] = gamma
u[N-1] = alpha

v = np.zeros(N)
v[0] = 1
v[N-1] = beta/gamma

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4.  2.  2.  2.  2.  2.  2.  2.  2.  1.5]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [56]:
L1,R1,y = s.tridiag_LU_decomp(a,b,c,vecb)

L2,R2,z = s.tridiag_LU_decomp(a,b,c,u)

x = y - s.matrix_dot(((s.matrix_dot(v,y))/(1+(s.matrix_dot(v,z)))),z)

print("Solution: ", x)

AttributeError: module 'shortcuts' has no attribute 'matrix_dot'