In [98]:
import numpy as np

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [99]:
a = np.asfarray([1,1,1,1,1,1,1,1,1,1])       #ignorier den ersten Wert
b = np.asfarray([2,2,2,2,2,2,2,2,2,2])
c = np.asfarray([-1,-1,-1,-1,-1,-1,-1,-1,-1,-1])        #ignorier den letzten Wert

vecb = np.array([1,-1,1,-1,1,-1,1,-1,1,-1])


N = np.shape(b)[0]

print(N)

10


In [100]:
alpha = c[N-1]
beta = a[0]
gamma = -b[0]

##########################################

b[0] = b[0] - gamma


b[N-1] = b[N-1] - (alpha*beta)/gamma


#a[1] = 0
#c[N-2] = 0

print(a)
print(b)
print(c)

u = np.zeros(N)
u[0] = gamma
u[N-1] = alpha

v = np.zeros(N)
v[0] = 1
v[N-1] = beta/gamma

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4.  2.  2.  2.  2.  2.  2.  2.  2.  1.5]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [101]:
s.tridiag_LU_decomp(a,b,c)

(array([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.25      , 1.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.44444444, 1.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.40909091, 1.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.41509434, 1.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.4140625 ,
         1.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.41423948, 1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.    

In [102]:
x = np.zeros(N)

y = np.zeros(N)

y[0] = vecb[0]

i = 1
while i < N:                          #Berechnung von y, FUNKTIONIERT, HABS GECHECKT
    j = 0
    y[i] = vecb[i]
    while j < i:
        y[i] -= L[i][j]*y[j]
        j += 1
    i += 1

#y = np.around(y,5)

#print(y)

x[N-1] = y[N-1]/(R[N-1][N-1])

i = N-2                                 #Berechnung von x, FUNKTIONIERT HABS GETESTET
while i >= 0:
    j = N-1
    x[i] = y[i]
    while j > i:
        x[i] -=  R[i][j]*x[j]
        j -= 1
    x[i] = x[i]/R[i][i]
    i -= 1


#x = np.around(x,5)

print("Das ist die Lösung x des LGS mit Tridiagonalen Matrizen: ", x)

Das ist die Lösung x des LGS mit Tridiagonalen Matrizen:  [ 0.17690355 -0.29238579  0.41522843 -0.46192893  0.49137056 -0.47918782
  0.53299492 -0.41319797  0.70659898 -1.13773266]
