In [1]:
import numpy as np
import math as m


In [3]:
A = np.asfarray([[3,-1,1,4,1],[1,0,1,1,1],[-1,-1,-1,-1,-1],[0,0,0,7,2],[3,4,-3,4,1]])
#print(np.matrix(A))
#print(np.shape(A))


dim = np.shape(A)[0]

b0 = np.asfarray([1,-1,1,-1,1])
b1 = np.asfarray([0,1,2,3,4])
#print(np.shape(b0))
#print(np.shape(b1))

Ainv = np.identity(dim)
#print(Ainv)



#############Aufgabe 1, 3x3 Matrix###########################

#A = np.asfarray([[3,3,6],[1,0,1],[2,2,3]])
#print(np.matrix(A))

#dim = np.shape(A)[0]

#Ainv = np.identity(dim)

#b0 = np.asfarray([-3,0,1])
#print(np.matrix(b0))
##############################################################

b = b0                                  #Wähle b aus

In [2]:
# #Blatt 3, Aufgabe 1b)

# A = np.asfarray([[1.1,1.7,1.3],[1.3,1.9,2.3],[2.1,3.1,2.9]])


# dim = np.shape(A)[0]

# b0 = np.asfarray([2.0,1.6,2.2])


# Ainv = np.identity(dim)


# b = b0                                  #Wähle b aus

In [3]:
############### Inverse Matrix berechnen FUNKTIONIERT!!!!! ######################################
i = 0
while i < dim:             #Damit ich gehe ich jede Zeile schrittweise durch

    if A[i][i] != 0:
        c = A[i][i]                 #c ist der Vorfaktor vor dem (i,i)-Eintrag der Matrix
        A[i] = A[i]/c            #Division der i-ten Zeile durch den Vorfaktor an Stelle i,i
        Ainv[i] = Ainv[i]/c       #Selbiges mit der i-ten Zeile in der Einheitsmatrix

        x = 0

        while x < dim:              #Damit gehe ich jede Zeile durch, die ich von der i-ten Zeile subtrahieren muss
            if x == i:
                x = x + 1
                continue

            k = A[x][i]           #Koeffizient mit dem ich die Zeile i multiplizieren muss, damit ich Zeile i von i+1 abziehen kann

            j = 0                   #Mit j gehe ich die Spalten alle durch

            while j < dim:          #Damit ich gehe ich jede Spalte j in EINER Zeile durch
                A[x][j] = A[x][j] - k*A[i][j]
                Ainv[x][j] = Ainv[x][j] - k*Ainv[i][j]
                j = j + 1
            x = x + 1

        i = i + 1
        #print(np.matrix(A))
        #print(np.matrix(Ainv))

    else:
        A[[i,i+1]] = A[[i+1,i]]
        Ainv[[i,i+1]] = Ainv[[i+1,i]]
        b[[i,i+1]] = b[[i+1,i]]


Ainv = np.around(Ainv,5)

print(np.matrix(A))

print(np.matrix(Ainv))


[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[[-22.5     -12.5      20.     ]
 [ 14.72222   6.38889 -11.66667]
 [  0.55556   2.22222  -1.66667]]


In [6]:
## x berechnen FUNKTIONIERT !!!! #################################
i = 0
x = np.zeros(dim)

while i < dim:
    buffer = 0
    j = 0
    while j < dim:
        buffer = buffer + Ainv[i][j]*b[j]
        j = j + 1
    x[i] += buffer
    i += 1

#x = np.around(x,5)
print(np.matrix(x))


[[-21.        13.99999    0.999998]]
