In [48]:
import numpy as np
import matplotlib.pyplot as plt

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [49]:
C = np.asfarray([[-2,5,4,1],[4,3,-3,6],[3,6,-3,-6],[1,0,1,1]])

dim = np.shape(C)[0]

C[0][0], C[0][1] = C[0][1], C[0][0]

print(C)

C[0] = C[0] + C[1]

print("\n",C)

for i in range(dim):
    C[0][i], C[1][i] = C[1][i], C[0][i]

print("\n",C)

print("\n", np.transpose(C))

[[ 5. -2.  4.  1.]
 [ 4.  3. -3.  6.]
 [ 3.  6. -3. -6.]
 [ 1.  0.  1.  1.]]

 [[ 9.  1.  1.  7.]
 [ 4.  3. -3.  6.]
 [ 3.  6. -3. -6.]
 [ 1.  0.  1.  1.]]

 [[ 4.  3. -3.  6.]
 [ 9.  1.  1.  7.]
 [ 3.  6. -3. -6.]
 [ 1.  0.  1.  1.]]

 [[ 4.  9.  3.  1.]
 [ 3.  1.  6.  0.]
 [-3.  1. -3.  1.]
 [ 6.  7. -6.  1.]]


In [50]:
C = np.asfarray([[-2,5,4,1],[4,3,-3,6],[3,6,-3,-6],[1,0,1,1]])

dim = np.shape(C)[0]

for r in range(dim-1):
    if r == 0:                      #so we start with r = 1
        continue
    M = 0
    rowprime = 0
    for i in range(dim):
        if i <= r-1:                  #make sure we search under the diagonal
            continue
        if np.abs(C[i][r-1]) > M:
            M = np.abs(C[i][r-1])
            rowprime = i
    #print("M:", M)
    if M > 0:
        for i in range(dim):
            C[i][r], C[i][rowprime] = C[i][rowprime], C[i][r]             #swap col
            C[r][i], C[rowprime][i] = C[rowprime][i], C[r][i]             #swap rows
        for i in range(dim):
            if i <= r:                        #so we start at i=r+1
                continue
            lamba = C[i][r-1]/C[r][r-1]
            #print("Lambda:", lamba)
            C[i] = C[i] - lamba*C[r]                  #row substraction
            for j in range(dim):
                C[j][r] = C[j][r] + lamba*C[j][i]                   #col addition


print(C)

[[ -2.           8.25         4.77777778   1.        ]
 [  4.           2.25         1.66666667   6.        ]
 [  0.           0.5625      -8.91666667 -10.5       ]
 [  0.           0.           8.2962963    7.66666667]]
