In [6]:
import numpy as np

import sys
sys.path.insert(0,"C:/Users/Dustin/Desktop/Numerische Methoden/VS Code/NM-Code-for-Excercises")
import shortcuts as s

In [7]:
A = np.asfarray([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]])

np.linalg.eig(A)[0]

array([3.73205081, 3.        , 2.        , 0.26794919, 1.        ])

In [13]:
def QL(A,precision):

    dim = np.shape(A)[0]

    # sum = 0                           just to check, whether A stays symmetric, yes it does

    delta = 1

    steps = 0

    while delta > precision:

        B = A

        Q = np.identity(dim)

        for i in range(dim-1):
            q = dim - 1 - i
            p = q - 1

            t = -((A[p][q])/(A[q][q]))
            #c = A[q][q]/((A[p][q]**2+A[q][q]**2)**0.5)
            #s = -A[q][p]/((A[q][p]**2+A[q][q]**2)**0.5)
            cos = 1/(((t**2)+1)**0.5)
            sin = t*cos
            P = np.identity(dim)
            P[p][p] = cos
            P[q][q] = cos
            P[p][q] = sin
            P[q][p] = -sin

            if i == 0:
                Q = s.transpose(P)
                #Q = np.transpose(P)
                continue

            #Q = np.dot(Q,np.transpose(P))
            Q = s.matrix_dot(Q, s.transpose(P))

        #Qt = np.transpose(Q)
        Qt = s.transpose(Q)

        #L = np.dot(Qt,A)
        L = s.matrix_dot(Qt,A)

        #A = np.dot(L,Q)
        A = s.matrix_dot(L,Q)

        delta = 0

        for j in range(dim):
            delta += np.abs(A[j][j]-B[j][j])

        steps += 1

        # for i in range(dim):
        #     for j in range(dim):
        #         if i == j:
        #             continue
        #         sum += A[i][j] - A[j][i]

    return A, steps#, sum

In [15]:
A = np.asfarray([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]])

dim = np.shape(A)[0]

Anew,steps = QL(A,1e-10)
#Anew = np.around(Anew,5)

for i in range(dim):
    print("Eigenvalue", i ," : " , Anew[i][i])

print("Steps: ", steps)

print(np.around(np.matrix(Anew),2))

# print(check)

Eigenvalue 0  :  0.2799368411647199
Eigenvalue 1  :  1.007102530658222
Eigenvalue 2  :  1.9901652905869922
Eigenvalue 3  :  2.991632667096466
Eigenvalue 4  :  3.7311626704936462
Steps:  55
[[ 0.28  0.    0.13  0.06  0.03]
 [ 0.    1.01 -0.    0.12 -0.  ]
 [ 0.13 -0.    1.99  0.    0.03]
 [ 0.06  0.12  0.    2.99 -0.  ]
 [ 0.03 -0.    0.03 -0.    3.73]]


In [41]:
def QL_new(A,precision):

    dim = np.shape(A)[0]

    # sum = 0                           just to check, whether A stays symmetric, yes it does

    delta = 1

    steps = 0

    while delta > precision:

        B = A

        for i in range(dim-1):
            q = dim - 1 - i
            p = q - 1

            t = -((A[p][q])/(A[q][q]))
            #c = A[q][q]/((A[p][q]**2+A[q][q]**2)**0.5)
            #s = -A[q][p]/((A[q][p]**2+A[q][q]**2)**0.5)
            cos = 1/(((t**2)+1)**0.5)
            sin = t*cos
            P = np.identity(dim)
            P[p][p] = cos
            P[q][q] = cos
            P[p][q] = sin
            P[q][p] = -sin

            A = np.dot(P,A)
            A = np.dot(A,np.transpose(P))

            for r in range(dim-2,0,1):                      #Givens Rotations to eliminate R
                t = A[r+1][r-1]/A[r+1][r]
                cos = 1/((t*t+1)**0.5)
                sin = t*cos
                P = np.identity(dim)
                P[r-1][r-1] = cos
                P[r][r] = cos
                P[r-1][r] = sin
                P[r][r-1] = -sin
                A = np.dot(P,A)
                A = np.dot(A,np.transpose(P))

        delta = 0

        for j in range(dim):
            delta += np.abs(A[j][j]-B[j][j])

        steps += 1

        if steps >= 1000:
            delta = 0

        # for i in range(dim):
        #     for j in range(dim):
        #         if i == j:
        #             continue
        #         sum += A[i][j] - A[j][i]

    return A, steps#, sum

In [43]:
A = np.asfarray([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]])

dim = np.shape(A)[0]

Anew,steps = QL_new(A,1e-10)
#Anew = np.around(Anew,5)

for i in range(dim):
    print("Eigenvalue", i ," : " , Anew[i][i])

print("Steps: ", steps)

print(np.around(np.matrix(Anew),2))

# print(check)

Eigenvalue 0  :  0.26794919243112286
Eigenvalue 1  :  1.0000000000000033
Eigenvalue 2  :  2.0000000000000084
Eigenvalue 3  :  3.000000000081439
Eigenvalue 4  :  3.732050807487457
Steps:  55
[[ 0.27 -0.   -0.    0.    0.  ]
 [ 0.    1.   -0.   -0.    0.  ]
 [ 0.    0.    2.   -0.   -0.  ]
 [ 0.    0.   -0.    3.   -0.  ]
 [-0.   -0.    0.   -0.    3.73]]
